wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701917470.554137
    t:
      1:
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.8.10
      5: 0.16.1
      6: 4.35.2
      8:
      - 5
      10:
      - 9
      13: linux-x86_64
